import assert from "node:assert/strict";
import { readdirSync } from "node:fs";
import test from "node:test";
import { canonicalizeBaselineValueV1, hashBaselineValueV1 } from "../baselineCanonicalizationV1";
import { projectLegacyDomainProfileSemanticPayloadV1 } from "../legacyDomainProfileSemanticPayloadV1";
import consultingFixture from "./fixtures/legacy-profile-projection-v1/legacy-consulting-v1.json";
import municipalFixture from "./fixtures/legacy-profile-projection-v1/legacy-municipal-v1.json";
import realEstateFixture from "./fixtures/legacy-profile-projection-v1/legacy-real-estate-v1.json";
import { hashLegacyProfileProjectionEnvelopeV1 } from "./hashLegacyProfileProjectionEnvelopeV1";
import { LEGACY_PROFILE_PROJECTION_V1_NESTED_FIELD_SHAPES, LEGACY_PROFILE_PROJECTION_V1_SOURCE_FIELD_ACCOUNTING } from "./legacyProfileProjectionV1";
import { parseLegacyProfileProjectionEnvelopeV1Structure } from "./parseLegacyProfileProjectionEnvelopeV1Structure";
import { projectLegacyProfilePayloadV1, projectLegacyProfileToDomainModelContractV1, projectLegacyProfileV1 } from "./projectLegacyProfileToDomainModelContractV1";

const PROFILES = ["legacy-real-estate-v1", "legacy-municipal-v1", "legacy-consulting-v1"] as const;
const FIXTURES = { "legacy-real-estate-v1": realEstateFixture, "legacy-municipal-v1": municipalFixture, "legacy-consulting-v1": consultingFixture } as const;
const SOURCE_HASHES = { "legacy-real-estate-v1": "sha256:898817bed271a470aecd941612a2bd49a95bec8acf480e5f645ffa0b9b5b33bc", "legacy-municipal-v1": "sha256:81ae1fa9f8a21a46c4cd04e4540c98db5750bd1305ecc6e215162d8da634193b", "legacy-consulting-v1": "sha256:b1bfcc87c86142264d3bd8d9082475720bdf3dcf8d7d7ec97583a5b40c5e08a7" } as const;
const ENVELOPE_HASHES = { "legacy-real-estate-v1": "sha256:27576f25895e0189fc33ab38e1572c0324ec9a9365f87041eecc46f8f343d855", "legacy-municipal-v1": "sha256:d682421748ee83d20bee3b4562bb993b0bf17cef291d8cb4325e565af854fcbd", "legacy-consulting-v1": "sha256:658381b072c2b0a82a8962ec7519376e997385ac5f02f5b7ee0cab6d7942cc6d" } as const;
const compareText = (left: string, right: string): number => left < right ? -1 : left > right ? 1 : 0;
const keys = (value: object): string[] => Object.keys(value).sort(compareText);
type Mutable<T> = T extends readonly (infer U)[] ? Mutable<U>[] : T extends object ? { -readonly [K in keyof T]: Mutable<T[K]> } : T;
function requireProjection(profileId: typeof PROFILES[number]) { const result = projectLegacyProfileV1(profileId); assert.equal(result.ok, true); if (!result.ok) throw new Error("Projection unexpectedly failed."); return result.value; }
function visitFrozen(value: unknown): void { if (value && typeof value === "object") { assert.equal(Object.isFrozen(value), true); Object.values(value).forEach(visitFrozen); } }

test("projects all three live legacy profiles through the complete validated pipeline", () => { for (const profileId of PROFILES) { const first = requireProjection(profileId), second = requireProjection(profileId); assert.deepEqual(first, second); assert.equal(canonicalizeBaselineValueV1(first), canonicalizeBaselineValueV1(second)); visitFrozen(first); } });
test("binds exact source and projected identities and independently recomputes source fixture hashes", () => { const domains = { "legacy-real-estate-v1": ["realEstate", "real-estate"], "legacy-municipal-v1": ["municipal", "municipal"], "legacy-consulting-v1": ["consulting", "consulting"] } as const; for (const profileId of PROFILES) { const source = projectLegacyDomainProfileSemanticPayloadV1(profileId), value = requireProjection(profileId).envelope; assert.equal(`sha256:${hashBaselineValueV1(source)}`, SOURCE_HASHES[profileId]); assert.equal(value.source.semanticPayloadHash, SOURCE_HASHES[profileId]); assert.equal(value.source.identity.domainId, domains[profileId][0]); assert.equal(value.projection.identity.domainId, domains[profileId][1]); assert.equal(value.projection.identity.profileId, `${profileId}-domain-model-contract-v1`); } });
test("projects exact native driver, action, effect, curve, edge, constraint and measure inventories", () => { for (const profileId of PROFILES) { const envelope = requireProjection(profileId).envelope, payload = envelope.projection.contract.semanticPayload; assert.equal(payload.drivers.length, 18); assert.equal(payload.curves.length, 18); assert.equal(new Set(payload.curves.map(value => value.curveId)).size, 18); assert.equal(payload.actions.length, profileId === "legacy-real-estate-v1" ? 8 : profileId === "legacy-municipal-v1" ? 6 : 9); assert.equal(payload.actions.some(value => value.actionId === "congestion_pricing"), false); assert.equal(payload.drivers.some(value => value.driverId === "liquidity-pressure"), false); assert.equal(payload.constraints.length, profileId === "legacy-municipal-v1" ? 0 : 1); assert.equal(payload.measures.length, 1); assert.equal(payload.measures[0].terms.length, 4); for (const action of payload.actions) assert.ok(action.effects.length > 0); for (const edge of payload.propagation.edges) assert.ok(payload.drivers.some(driver => driver.driverId === edge.sourceDriverId) && payload.drivers.some(driver => driver.driverId === edge.targetDriverId)); } });
test("projects exact profile-local compatibility and all six gap tuple occurrences", () => { let tuples = 0; const ids = new Set<string>(); for (const profileId of PROFILES) { const value = requireProjection(profileId).envelope.compatibility; assert.deepEqual(value.excludedUnsupportedActionIds, [...value.excludedUnsupportedActionIds].sort(compareText)); assert.equal(value.compatibilityOnlyActions.length, profileId === "legacy-real-estate-v1" ? 0 : 1); assert.equal(value.propagation.sourceEvaluationOrder.length, profileId === "legacy-municipal-v1" ? 3 : 20); assert.equal(value.propagation.compatibilityOnlyEdges.length, profileId === "legacy-municipal-v1" ? 0 : 3); for (const tuple of value.ignoredUnknownDriverDeltas) { tuples += 1; ids.add(tuple.sourceDriverId); } for (const action of value.compatibilityOnlyActions) for (const effect of action.ignoredEffects) { tuples += 1; ids.add(effect.driverId); } } assert.equal(tuples, 6); assert.deepEqual([...ids].sort(compareText), ["implementationPacingRisk", "liquidityPressure", "modal_shift_pressure", "political_feasibility"].sort(compareText)); });
test("accounts exhaustively for every enumerable source field family", () => { assert.deepEqual(keys(LEGACY_PROFILE_PROJECTION_V1_SOURCE_FIELD_ACCOUNTING), ["actions", "applicableDrivers", "clampPolicy", "constraints", "curveConfiguration", "defaultState", "identity", "impactContract", "marginEscalationRules", "propagationRelationships", "schemaVersion", "supportedActionIds"]); for (const profileId of PROFILES) { const source = projectLegacyDomainProfileSemanticPayloadV1(profileId); assert.deepEqual(keys(source), keys(LEGACY_PROFILE_PROJECTION_V1_SOURCE_FIELD_ACCOUNTING)); assert.deepEqual(keys(source.identity), LEGACY_PROFILE_PROJECTION_V1_NESTED_FIELD_SHAPES.identity); assert.deepEqual(keys(source.actions[0]), LEGACY_PROFILE_PROJECTION_V1_NESTED_FIELD_SHAPES.action); assert.deepEqual(keys(source.propagationRelationships[0]), LEGACY_PROFILE_PROJECTION_V1_NESTED_FIELD_SHAPES.propagationRelationship); assert.deepEqual(keys(source.propagationRelationships[0].targets[0]), LEGACY_PROFILE_PROJECTION_V1_NESTED_FIELD_SHAPES.propagationTarget); assert.deepEqual(keys(source.constraints), LEGACY_PROFILE_PROJECTION_V1_NESTED_FIELD_SHAPES.constraints); assert.deepEqual(keys(source.impactContract[0]), LEGACY_PROFILE_PROJECTION_V1_NESTED_FIELD_SHAPES.impactContractEntry); assert.deepEqual(keys(source.impactContract[0].impacts[0]), LEGACY_PROFILE_PROJECTION_V1_NESTED_FIELD_SHAPES.impact); assert.deepEqual(keys(Object.values(source.curveConfiguration)[0]), LEGACY_PROFILE_PROJECTION_V1_NESTED_FIELD_SHAPES.curveConfigurationEntry); assert.deepEqual(keys(Object.values(source.curveConfiguration)[0].amplitude), LEGACY_PROFILE_PROJECTION_V1_NESTED_FIELD_SHAPES.amplitude); assert.deepEqual(keys(source.clampPolicy), LEGACY_PROFILE_PROJECTION_V1_NESTED_FIELD_SHAPES.clampPolicy); assert.deepEqual(keys(source.defaultState), [...source.applicableDrivers].sort(compareText)); assert.deepEqual(keys(source.curveConfiguration), [...source.applicableDrivers].sort(compareText)); assert.deepEqual(source.impactContract.map(entry => entry.key).sort(compareText), [...source.applicableDrivers].sort(compareText)); assert.deepEqual(keys(source.constraints.activeEffects), ["CovenantConstraint", "LiquidityConstraint", "RefinancingConstraint"]); for (const action of source.actions) assert.ok(Object.keys(action.driverDeltas).length > 0); for (const rule of source.marginEscalationRules) assert.deepEqual(keys(rule), LEGACY_PROFILE_PROJECTION_V1_NESTED_FIELD_SHAPES.marginEscalationRule); } });
test("rejects unknown, missing, extra or changed locked source data fail-closed", () => { assert.deepEqual(projectLegacyProfileV1("unknown"), { ok: false, code: "unknown-legacy-profile", message: "Unknown legacy profile: unknown" }); const source = structuredClone(projectLegacyDomainProfileSemanticPayloadV1("legacy-real-estate-v1")) as Mutable<ReturnType<typeof projectLegacyDomainProfileSemanticPayloadV1>>; for (const mutate of [(value: typeof source) => { value.identity.modelVersion = "changed"; }, (value: typeof source) => { Reflect.deleteProperty(value.identity, "domainId"); }, (value: typeof source) => { Reflect.set(value, "extra", true); }, (value: typeof source) => { value.curveConfiguration.demandRisk.amplitude.high += .01; }]) { const changed = structuredClone(source); mutate(changed); assert.equal(projectLegacyProfilePayloadV1(changed).ok, false); } });
test("is neutral to object insertion order but preserves legacy propagation array order", () => { const source = structuredClone(projectLegacyDomainProfileSemanticPayloadV1("legacy-real-estate-v1")) as Mutable<ReturnType<typeof projectLegacyDomainProfileSemanticPayloadV1>>; source.identity = { profileId: source.identity.profileId, calibrationVersion: source.identity.calibrationVersion, domainId: source.identity.domainId, modelVersion: source.identity.modelVersion }; assert.equal(projectLegacyProfilePayloadV1(source).ok, true); source.propagationRelationships.reverse(); assert.equal(projectLegacyProfilePayloadV1(source).ok, false); });
test("does not mutate live source and returns detached output", () => { for (const profileId of PROFILES) { const source = structuredClone(projectLegacyDomainProfileSemanticPayloadV1(profileId)), before = structuredClone(source), contract = projectLegacyProfileToDomainModelContractV1(source); assert.deepEqual(source, before); assert.notEqual(contract.semanticPayload.drivers, source.applicableDrivers); } });
test("reproduces exactly three checked-in fixtures through the real adapter", () => { assert.deepEqual(readdirSync(new URL("./fixtures/legacy-profile-projection-v1", import.meta.url)).sort(compareText), PROFILES.map(profileId => `${profileId}.json`).sort(compareText)); assert.equal(Object.keys(FIXTURES).length, 3); for (const profileId of PROFILES) { const value = requireProjection(profileId).envelope; assert.deepEqual(value, FIXTURES[profileId]); const parsed = parseLegacyProfileProjectionEnvelopeV1Structure(FIXTURES[profileId]); assert.equal(parsed.ok, true); } });
test("locks deterministic envelope hashes as M1C-3a computed, not independently M1C-3b verified", () => { for (const profileId of PROFILES) assert.equal(hashLegacyProfileProjectionEnvelopeV1(requireProjection(profileId).envelope), ENVELOPE_HASHES[profileId]); });
test("locks exact binary64 materialization boundaries", () => { const scale = requireProjection("legacy-real-estate-v1").envelope.projection.contract.semanticPayload.scales[0]; assert.deepEqual(scale.levels.map(value => value.materialization), [{ minimumInclusive: 0, maximumExclusive: .5000000000000001 }, { minimumInclusive: .5000000000000001, maximumExclusive: 1.5 }, { minimumInclusive: 1.5, maximumExclusive: 2.5 }, { minimumInclusive: 2.5, maximumInclusive: 3 }]); });
