import { canonicalizeBaselineValueV1, hashBaselineValueV1 } from "../baselineCanonicalizationV1";
import { projectLegacyDomainProfileSemanticPayloadV1, type LegacyDomainProfileSemanticPayloadV1 } from "../legacyDomainProfileSemanticPayloadV1";
import type { CurveDefinition, DomainModelContractV1, DriverImpact } from "./contractV1";
import type { ExcludedSourceValueV1, RawLegacyProfileProjectionEnvelopeV1, ValidatedLegacyProfileProjectionEnvelopeV1 } from "./legacyProfileProjectionEnvelopeV1";
import { hashLegacyCompatibilityIdentityV1, validateLegacyProfileProjectionEnvelopeV1 } from "./hashLegacyProfileProjectionEnvelopeV1";
import { hashDomainModelContractSemanticIdentityV1 } from "./domainModelContractSemanticIdentityV1";
import { parseDomainModelContractV1Structure } from "./parseDomainModelContractV1Structure";
import { parseLegacyProfileProjectionEnvelopeV1Structure } from "./parseLegacyProfileProjectionEnvelopeV1Structure";
import { LEGACY_DRIVER_ID_MAPPINGS_V1, type LegacyProfileIdV1, validateLegacyProfileProjectionEnvelopeV1Semantics } from "./validateLegacyProfileProjectionEnvelopeV1Semantics";

export type LegacyProfileProjectionV1Result = Readonly<{ ok: true; value: ValidatedLegacyProfileProjectionEnvelopeV1 }> | Readonly<{ ok: false; code: "unknown-legacy-profile" | "projection-invalid"; message: string }>;

const PROFILE_IDS: readonly LegacyProfileIdV1[] = ["legacy-real-estate-v1", "legacy-municipal-v1", "legacy-consulting-v1"];
const DRIVER_IDS = new Map<string, string>(LEGACY_DRIVER_ID_MAPPINGS_V1);
const BENEFIT_DRIVERS = new Set(["accessibility", "modal_attractiveness", "operational_capacity", "transit_signal_priority"]);
const ZERO_HASH = `sha256:${"0".repeat(64)}` as const;

function compareText(left: string, right: string): number { return left < right ? -1 : left > right ? 1 : 0; }
function isProfileId(value: string): value is LegacyProfileIdV1 { return PROFILE_IDS.some(profileId => profileId === value); }
function mappedDriver(id: string): string { return DRIVER_IDS.get(id) ?? (id === "liquidityPressure" ? "liquidity-pressure" : id); }
function level(id: string): "low" | "moderate" | "high" | "severe" {
  if (id === "LOW") return "low"; if (id === "MODERATE") return "moderate"; if (id === "HIGH") return "high"; if (id === "SEVERE") return "severe";
  throw new Error(`Unknown legacy level: ${id}`);
}
function direction(value: string): DriverImpact["direction"] { if (value === "increase" || value === "decrease") return value; throw new Error(`Unknown impact direction: ${value}`); }
function curve(sourceId: string, projectedId: string, source: LegacyDomainProfileSemanticPayloadV1): CurveDefinition {
  const configuration = source.curveConfiguration[sourceId];
  if (!configuration) throw new Error(`Missing curve configuration: ${sourceId}`);
  const common = { curveId: `legacy-curve-v1.${projectedId}`, amplitudeByLevel: { low: configuration.amplitude.low, moderate: configuration.amplitude.base, high: configuration.amplitude.high, severe: configuration.amplitude.severe } };
  if (configuration.curve === "LINEAR") return { ...common, type: "linear" };
  if (configuration.curve === "EXPONENTIAL") return { ...common, type: "exponential", exponent: 1.2 };
  if (configuration.curve === "LOGISTIC") return { ...common, type: "logistic", k: .8, x0: 3 };
  throw new Error(`Unsupported legacy curve: ${configuration.curve}`);
}

export function projectLegacyProfileToDomainModelContractV1(source: LegacyDomainProfileSemanticPayloadV1): DomainModelContractV1 {
  const projectedDomain = source.identity.domainId === "realEstate" ? "real-estate" : source.identity.domainId;
  const drivers = source.applicableDrivers.map(sourceId => {
    const projectedId = DRIVER_IDS.get(sourceId); if (!projectedId) throw new Error(`Unmapped applicable driver: ${sourceId}`);
    const impact = source.impactContract.find(entry => entry.key === sourceId); if (!impact) throw new Error(`Missing impact contract: ${sourceId}`);
    const initialLevel = source.defaultState[sourceId]; if (initialLevel !== "MODERATE") throw new Error(`Unsupported default state: ${sourceId}`);
    return { driverId: projectedId, scaleId: "legacy-risk-scale-v1", initial: { levelId: level(initialLevel), score: 1 }, numericRange: { minimum: 0, maximum: 3 }, adverseLevelIds: BENEFIT_DRIVERS.has(sourceId) ? ["low"] : ["high", "severe"], impacts: impact.impacts.map(value => ({ dimensionId: value.dimension, direction: direction(value.direction), curveId: `legacy-curve-v1.${projectedId}` })) };
  });
  const admitted = new Set(source.supportedActionIds);
  const actions = source.actions.filter(action => admitted.has(action.actionId) && action.actionId !== "congestion_pricing").map(action => ({ actionId: action.actionId, effects: Object.entries(action.driverDeltas).filter(([driverId]) => DRIVER_IDS.has(driverId)).map(([driverId, delta]) => ({ driverId: mappedDriver(driverId), delta })) }));
  const edges = source.propagationRelationships.flatMap(group => group.targets.map(target => ({ group, target }))).filter(({ group, target }) => group.source !== "liquidityPressure" && target.target !== "liquidityPressure").map(({ group, target }) => ({ edgeId: `legacy-edge-v1.${mappedDriver(group.source)}.to.${mappedDriver(target.target)}`, sourceDriverId: mappedDriver(group.source), targetDriverId: mappedDriver(target.target), triggerLevelIds: BENEFIT_DRIVERS.has(group.source) ? ["low"] : ["high", "severe"], propagatedLevelId: level(target.level) }));
  const refinancingEffects = source.constraints.activeEffects.RefinancingConstraint;
  const constraints = source.constraints.refinancingEnabled ? [{ constraintId: "refinancing-constraint", initialLifecycle: "inactive" as const, activation: { kind: "measure-below" as const, measureId: "structural-margin", threshold: source.constraints.refinancingMarginThreshold }, sustain: { kind: "until-explicit-transition" as const }, deactivation: { kind: "none" as const }, allowedTransitions: [{ from: "inactive" as const, to: "active" as const }, { from: "recovering" as const, to: "active" as const }], activeEffects: Object.entries(refinancingEffects).map(([dimensionId, value]) => ({ dimensionId, operation: "multiply" as const, value })) }] : [];
  const escalationRules = source.marginEscalationRules.map(rule => ({ whenBelow: rule.marginBelow, driverId: mappedDriver(rule.driver), transitions: [{ fromLevelId: "low", toLevelId: level(rule.lowTarget) }, { fromLevelId: "moderate", toLevelId: level(rule.moderateTarget) }] }));
  return { schemaVersion: "domain-model-contract-v1", engineProtocolVersion: "pulse-domain-engine-protocol-v1", identity: { domainId: projectedDomain, profileId: `${source.identity.profileId}-domain-model-contract-v1`, modelVersion: `${source.identity.modelVersion}-domain-model-contract-v1`, calibrationVersion: `${source.identity.calibrationVersion}-domain-model-contract-v1`, semanticPayloadHash: ZERO_HASH }, semanticPayload: { scales: [{ scaleId: "legacy-risk-scale-v1", levels: [{ levelId: "low", rank: 0, anchor: 0, materialization: { minimumInclusive: 0, maximumExclusive: .5000000000000001 } }, { levelId: "moderate", rank: 1, anchor: 1, materialization: { minimumInclusive: .5000000000000001, maximumExclusive: 1.5 } }, { levelId: "high", rank: 2, anchor: 2, materialization: { minimumInclusive: 1.5, maximumExclusive: 2.5 } }, { levelId: "severe", rank: 3, anchor: 3, materialization: { minimumInclusive: 2.5, maximumInclusive: 3 } }] }], drivers, actions, propagation: { edges, cyclePolicy: "reject", selfEdgePolicy: "reject", duplicateEdgePolicy: "reject" }, dimensions: ["load", "cost", "recovery", "sensitivity"].map(dimensionId => ({ dimensionId, neutralValue: 1 })), curves: source.applicableDrivers.map(sourceId => curve(sourceId, mappedDriver(sourceId), source)), constraints, measures: [{ measureId: "structural-margin", kind: "weighted-signal-aggregate-v1", updateOperator: "subtract-terms-add-recovery-v1", initialValue: 1, terms: [{ termId: "adjusted-cost", source: { kind: "dimension", dimensionId: "cost", stage: "after-constraints" }, transform: "deviation-from-neutral", weight: 1.2 }, { termId: "adjusted-recovery", source: { kind: "dimension", dimensionId: "recovery", stage: "after-constraints" }, transform: "inverse-from-neutral", weight: 1.1 }, { termId: "positive-adjusted-load", source: { kind: "dimension", dimensionId: "load", stage: "after-constraints" }, transform: "positive-deviation-from-neutral", weight: .45 }, { termId: "base-pressure", source: { kind: "protocol-signal", signalId: "base-dimension-pressure-sum-v1" }, transform: "identity", weight: .8 }], recovery: { targetValue: 1, pull: .12 }, range: { minimum: source.clampPolicy.minimum, maximum: source.clampPolicy.maximum }, escalationRules }] } };
}

function compatibilityWithoutAdmission(source: LegacyDomainProfileSemanticPayloadV1, profileId: LegacyProfileIdV1): Omit<RawLegacyProfileProjectionEnvelopeV1["compatibility"], "declarationsHash" | "actionAdmission"> {
  const order = source.propagationRelationships.flatMap((group, sourcePosition) => group.targets.map((target, edgePosition) => ({ sourcePosition, edgePosition, sourceLegacyDriverId: group.source, targetLegacyDriverId: target.target, projectedOrCompatibilityEdgeId: `${group.source === "liquidityPressure" || target.target === "liquidityPressure" ? "legacy-compat-edge-v1" : "legacy-edge-v1"}.${mappedDriver(group.source)}.to.${mappedDriver(target.target)}` })));
  const compatibilityOnlyEdges = source.propagationRelationships.flatMap((group, sourcePosition) => group.targets.map((target, edgePosition) => ({ group, target, sourcePosition, edgePosition }))).filter(({ group, target }) => group.source === "liquidityPressure" || target.target === "liquidityPressure").map(({ group, target, sourcePosition, edgePosition }) => ({ sourcePosition, edgePosition, occurrencePosition: order.findIndex(entry => entry.sourcePosition === sourcePosition && entry.edgePosition === edgePosition), sourceLegacySourceDriverId: group.source, sourceLegacyTargetDriverId: target.target, adapterLocalSourceDriverId: mappedDriver(group.source), adapterLocalTargetDriverId: mappedDriver(target.target), compatibilityEdgeId: `legacy-compat-edge-v1.${mappedDriver(group.source)}.to.${mappedDriver(target.target)}`, sourcePropagatedLevelId: target.level, projectedPropagatedLevelId: level(target.level), triggerPredicate: "source-level-in-set-v1" as const, triggerLevelIds: ["high", "severe"] as const }));
  const congestion = source.actions.find(action => action.actionId === "congestion_pricing"); if (!congestion) throw new Error("Missing congestion_pricing source action.");
  const compatibilityOnlyActions = profileId === "legacy-real-estate-v1" ? [] : [{ kind: "legacy-compatibility-only-action-v1" as const, sourceProfileId: profileId, sourceActionId: congestion.actionId, projectedNativeAction: "omitted-because-no-modeled-effects" as const, admission: "legacy-adapter-only" as const, ignoredEffects: Object.entries(congestion.driverDeltas).map(([driverId, delta]) => ({ driverId, delta })) }];
  const ignoredUnknownDriverDeltas = profileId === "legacy-real-estate-v1" ? ["stagger_project_starts", "increase_liquidity_buffer"].flatMap(sourceActionId => { const action = source.actions.find(candidate => candidate.actionId === sourceActionId); if (!action) throw new Error(`Missing source action: ${sourceActionId}`); return Object.entries(action.driverDeltas).filter(([driverId]) => !DRIVER_IDS.has(driverId)).map(([sourceDriverId, delta]) => ({ sourceProfileId: profileId, sourceActionId: action.actionId, sourceDriverId, delta })); }) : [];
  const effects = source.constraints.activeEffects; const excludedSourceValues: ExcludedSourceValueV1[] = [{ kind: "provably-unreachable-public-execution-v1", sourcePath: "constraints.LiquidityConstraint", sourceValueHash: `sha256:${hashBaselineValueV1(effects.LiquidityConstraint)}`, reasonCode: "no-public-activation-transition" }, { kind: "provably-unreachable-public-execution-v1", sourcePath: "constraints.CovenantConstraint", sourceValueHash: `sha256:${hashBaselineValueV1(effects.CovenantConstraint)}`, reasonCode: "no-public-activation-transition" }, { kind: "provably-unreachable-public-execution-v1", sourcePath: "constraints.Custom", sourceValueHash: `sha256:${hashBaselineValueV1({ type: "Custom", lifecycle: "INACTIVE", lastUpdatedStep: 0 })}`, reasonCode: "inert-global-registry-member" }];
  if (!source.constraints.refinancingEnabled) excludedSourceValues.unshift({ kind: "provably-unreachable-public-execution-v1", sourcePath: "constraints.RefinancingConstraint", sourceValueHash: `sha256:${hashBaselineValueV1({ enabled: false, threshold: source.constraints.refinancingMarginThreshold, effects: effects.RefinancingConstraint })}`, reasonCode: "profile-constraint-disabled" });
  return { declarationsVersion: "legacy-compatibility-declarations-v1", ignoredUnknownDriverDeltas, compatibilityOnlyActions, driverIdMappings: LEGACY_DRIVER_ID_MAPPINGS_V1.map(([sourceDriverId, projectedDriverId]) => ({ sourceDriverId, projectedDriverId })), excludedUnsupportedActionIds: source.actions.map(action => action.actionId).filter(actionId => !source.supportedActionIds.includes(actionId)).sort(compareText), sustainThresholdDisposition: source.constraints.refinancingEnabled ? { kind: "legacy-sustain-threshold-exclusion-v1", sourceField: "sustainThreshold", historicalObservation: { kind: "optional-runtime-field-read-observed-v1", constraintId: "refinancing-constraint", observedRuntimeType: "number-including-non-finite", observedComparison: "margin-strictly-below-threshold" }, valueStatus: "absent-unconfigured", contractDisposition: "excluded-no-authoritative-value", executionPolicy: "reject-at-equivalence-boundary-v1", claimPolicy: "no-sustain-parity-v1", futureSupport: "requires-versioned-amendment-and-authoritative-value-source-v1" } : null, propagation: { edgeEvaluationOrder: "legacy-source-and-target-insertion-order-v1", executionSemantics: { algorithm: "ordered-monotone-raise-fixed-point-v1", sourceReadPolicy: "missing-source-does-not-trigger-v1", targetReadPolicy: "missing-target-uses-declared-default-v1", targetComparison: "propagated-rank-strictly-greater-v1", writeVisibility: "later-occurrences-same-iteration-v1", iterationPolicy: "repeat-from-start-until-no-raise-v1", eventPolicy: { emission: "on-target-level-change-v1", step: "iteration-plus-one-v1", delaySteps: 1, duplicateSuppression: "no-change-no-event-v1" } }, implicitNode: compatibilityOnlyEdges.length ? { sourceNodeId: "liquidityPressure", adapterLocalNodeId: "liquidity-pressure", initialLevel: "absent", initialScore: "absent", targetMissingDefaultLevelId: "low", materialization: "on-propagation-raise-v1", scoreMaterialization: "projected-level-anchor-after-propagation-v1", impacts: "none" } : null, sourceEvaluationOrder: order, compatibilityOnlyEdges }, excludedSourceValues, legacyRegistryProjection: registryProjection(profileId), curveFallbackDeclaration: { policyId: "legacy-neutral-multiplier-v1", appliesTo: ["missing-curve-configuration", "unsupported-curve-discriminant"], neutralMultiplier: 1, evidenceStatus: "deferred-to-m1e" } };
}

function actionAdmission(source: LegacyDomainProfileSemanticPayloadV1, profileId: LegacyProfileIdV1): RawLegacyProfileProjectionEnvelopeV1["compatibility"]["actionAdmission"] {
  const requested = profileId === "legacy-real-estate-v1" ? ["increase_liquidity_buffer", "stagger_project_starts"] : ["congestion_pricing"];
  const entries = requested.map(sourceActionId => {
    const action = source.actions.find(candidate => candidate.actionId === sourceActionId);
    if (!action) throw new Error(`Missing action-admission source action: ${sourceActionId}`);
    const retainedEffects = Object.entries(action.driverDeltas).filter(([sourceDriverId]) => DRIVER_IDS.has(sourceDriverId)).map(([sourceDriverId, delta]) => ({ sourceDriverId, projectedDriverId: DRIVER_IDS.get(sourceDriverId)!, delta, disposition: "apply-to-projected-native-driver-v1" as const })).sort((a,b)=>compareText(a.projectedDriverId,b.projectedDriverId));
    const ignoredEffects = Object.entries(action.driverDeltas).filter(([sourceDriverId]) => !DRIVER_IDS.has(sourceDriverId)).map(([sourceDriverId, delta]) => ({ sourceDriverId, delta, disposition: "ignore-without-state-node-v1" as const, reason: "driver-absent-from-native-contract-v1" as const })).sort((a,b)=>compareText(a.sourceDriverId,b.sourceDriverId));
    return { entryId: `legacy-action-admission-v1.${profileId}.${sourceActionId}`, sourceProfileId: profileId, sourceActionId, admissionMode: "admit-after-exact-effect-partition-v1" as const, outputDisposition: retainedEffects.length ? "retained-native-effects-v1" as const : "output-neutral-v1" as const, retainedEffects, ignoredEffects };
  }).sort((a,b)=>compareText(a.sourceActionId,b.sourceActionId));
  return { schemaVersion:"legacy-action-admission-policy-v1", protocol:"partition-source-effects-before-execution-v1", scheduleInput:"source-action-id-and-execution-step-v1", ordering:"execution-step-then-source-action-id-code-unit-v1", duplicatePolicy:"reject-duplicate-source-action-per-scenario-v1", undeclaredActionPolicy:"reject-before-execution-v1", undeclaredEffectPolicy:"reject-before-execution-v1", normalizationFailurePolicy:"atomic-no-output-no-provenance-v1", actualRuntimeExpectation:"reject-unsupported-driver-before-step-v1", normalizedProvenancePolicy:"separate-closed-compatibility-provenance-v1", entries };
}

function compatibility(source: LegacyDomainProfileSemanticPayloadV1, profileId: LegacyProfileIdV1): Omit<RawLegacyProfileProjectionEnvelopeV1["compatibility"], "declarationsHash"> {
  return { actionAdmission: actionAdmission(source, profileId), ...compatibilityWithoutAdmission(source, profileId) };
}

const REGISTRY_TUPLES = Object.freeze([
  ["RefinancingConstraint", "legacy-registry-entry-v1.refinancing-constraint"],
  ["LiquidityConstraint", "legacy-registry-entry-v1.liquidity-constraint"],
  ["CovenantConstraint", "legacy-registry-entry-v1.covenant-constraint"],
  ["Custom", "legacy-registry-entry-v1.custom"],
] as const);
function registryProjection(profileId:LegacyProfileIdV1):RawLegacyProfileProjectionEnvelopeV1["compatibility"]["legacyRegistryProjection"]{const tuples=profileId==="legacy-municipal-v1"?REGISTRY_TUPLES:REGISTRY_TUPLES.slice(1);return {version:"legacy-registry-projection-compatibility-v1",registryOrder:"legacy-constraint-registry-constructor-order-v1",materialization:{scenarios:["scenarioA","scenarioB","baseline"],surfaces:["trajectory.registry","constraintHistory","terminalState.registry"],cadence:"initial-and-every-completed-step-v1"},entries:tuples.map(([key,id])=>({kind:"legacy-inert-registry-entry-v1",sourceProfileId:profileId,sourceRegistryKey:key,compatibilityEntryId:id,legacyType:key,initialState:{lifecycle:"INACTIVE",activatedAtStep:"absent",lastUpdatedStep:0},transitionPolicy:"no-public-transition-v1",executionPolicy:"immutable-inert-output-placeholder-v1",sourceEvidence:{constructorPath:"src/pilotFastighet/constraintState.ts#createInitialConstraintRegistry",excludedSourcePath:`constraints.${key}`,initialRegistryStateHash:`sha256:${hashBaselineValueV1({type:key,lifecycle:"INACTIVE",lastUpdatedStep:0})}`}}))};}

export function projectLegacyProfileV1(profileId: string): LegacyProfileProjectionV1Result {
  if (!isProfileId(profileId)) return Object.freeze({ ok: false, code: "unknown-legacy-profile", message: `Unknown legacy profile: ${profileId}` });
  try {
    const source = projectLegacyDomainProfileSemanticPayloadV1(profileId); const contract = projectLegacyProfileToDomainModelContractV1(source);
    const parsedContract = parseDomainModelContractV1Structure(contract); if (!parsedContract.ok) throw new Error("Projected contract failed structural validation.");
    const envelope: RawLegacyProfileProjectionEnvelopeV1 = { schemaVersion: "legacy-profile-projection-v1", adapterVersion: "legacy-domain-profile-adapter-v1", engineProtocolVersion: "pulse-domain-engine-protocol-v1", source: { identity: structuredClone(source.identity), semanticPayloadVersion: "legacy-domain-profile-semantic-payload-v1", semanticPayloadHash: `sha256:${hashBaselineValueV1(source)}` }, projection: { identity: structuredClone(contract.identity), semanticPayloadHashPolicy: "domain-model-contract-v1-semantic-payload-v1", semanticPayloadHash: ZERO_HASH, contract }, compatibility: { declarationsHash: ZERO_HASH, ...compatibility(source, profileId) } };
    let structural = parseLegacyProfileProjectionEnvelopeV1Structure(envelope); if (!structural.ok) throw new Error(`Envelope failed structural validation: ${structural.issues.map(issue => `${issue.code}@${issue.path}`).join(",")}`); let semantic = validateLegacyProfileProjectionEnvelopeV1Semantics(structural.value); if (!semantic.ok) throw new Error(`Envelope failed semantic validation: ${semantic.issues.map(issue => `${issue.code}@${issue.path}`).join(",")}`);
    const projectedHash = hashDomainModelContractSemanticIdentityV1(semantic.value.projection.contract); const hashedEnvelope: RawLegacyProfileProjectionEnvelopeV1 = { ...structuredClone(envelope), projection: { ...structuredClone(envelope.projection), identity: { ...structuredClone(envelope.projection.identity), semanticPayloadHash: projectedHash }, semanticPayloadHash: projectedHash, contract: { ...structuredClone(envelope.projection.contract), identity: { ...structuredClone(envelope.projection.contract.identity), semanticPayloadHash: projectedHash } } } };
    structural = parseLegacyProfileProjectionEnvelopeV1Structure(hashedEnvelope); if (!structural.ok) throw new Error("Hashed envelope failed structural validation."); semantic = validateLegacyProfileProjectionEnvelopeV1Semantics(structural.value); if (!semantic.ok) throw new Error("Hashed envelope failed semantic validation."); const declarationsHash = hashLegacyCompatibilityIdentityV1(semantic.value); const finalEnvelope: RawLegacyProfileProjectionEnvelopeV1 = { ...structuredClone(hashedEnvelope), compatibility: { ...structuredClone(hashedEnvelope.compatibility), declarationsHash } };
    structural = parseLegacyProfileProjectionEnvelopeV1Structure(finalEnvelope); if (!structural.ok) throw new Error("Final envelope failed structural validation."); const validated = validateLegacyProfileProjectionEnvelopeV1(structural.value); if (!validated.ok) throw new Error("Final envelope failed hash validation."); return Object.freeze({ ok: true, value: validated.value });
  } catch (error) { return Object.freeze({ ok: false, code: "projection-invalid", message: error instanceof Error ? error.message : "Projection failed." }); }
}

export function projectLegacyProfilePayloadV1(input: unknown): LegacyProfileProjectionV1Result {
  if (!input || typeof input !== "object" || Array.isArray(input)) return Object.freeze({ ok: false, code: "projection-invalid", message: "Legacy source payload must be an object." });
  const identity = Object.getOwnPropertyDescriptor(input, "identity");
  if (!identity || !("value" in identity) || !identity.value || typeof identity.value !== "object" || Array.isArray(identity.value)) return Object.freeze({ ok: false, code: "projection-invalid", message: "Legacy source identity is missing." });
  const profile = Object.getOwnPropertyDescriptor(identity.value, "profileId");
  if (!profile || !("value" in profile) || typeof profile.value !== "string" || !isProfileId(profile.value)) return Object.freeze({ ok: false, code: "unknown-legacy-profile", message: "Legacy source profile identity is unknown." });
  try {
    const locked = projectLegacyDomainProfileSemanticPayloadV1(profile.value);
    if (canonicalizeBaselineValueV1(input, "$legacySource") !== canonicalizeBaselineValueV1(locked, "$legacySource")) return Object.freeze({ ok: false, code: "projection-invalid", message: "Legacy source payload differs from its locked profile." });
    return projectLegacyProfileV1(profile.value);
  } catch (error) { return Object.freeze({ ok: false, code: "projection-invalid", message: error instanceof Error ? error.message : "Projection failed." }); }
}
