import { canonicalizeBaselineValueV1, hashBaselineValueV1 } from "../baselineCanonicalizationV1";
import consultingFixture from "../fixtures/legacy-domain-profile-semantic-payload-v1/legacy-consulting-v1.json";
import municipalFixture from "../fixtures/legacy-domain-profile-semantic-payload-v1/legacy-municipal-v1.json";
import realEstateFixture from "../fixtures/legacy-domain-profile-semantic-payload-v1/legacy-real-estate-v1.json";
import type { DomainModelContractV1 } from "./contractV1";
import { sortContractIssues, type ContractIssue } from "./contractV1Issues";
import { canonicalizeDomainModelContractSemanticIdentityV1 } from "./domainModelContractSemanticIdentityV1";
import type { RawLegacyProfileProjectionEnvelopeV1, SemanticallyValidatedLegacyProfileProjectionEnvelopeV1, StructurallyValidatedLegacyProfileProjectionEnvelopeV1 } from "./legacyProfileProjectionEnvelopeV1";
import { parseDomainModelContractV1Structure } from "./parseDomainModelContractV1Structure";
import { validateDomainModelContractV1Semantics } from "./validateDomainModelContractV1Semantics";

export const LEGACY_PROFILE_PROJECTION_ENVELOPE_V1_SEMANTIC_ISSUE_CODES = Object.freeze([
  "compatibility-action-mismatch", "compatibility-declaration-mismatch", "constraint-projection-mismatch",
  "curve-projection-mismatch", "driver-mapping-collision", "driver-mapping-mismatch",
  "driver-projection-mismatch", "legacy-propagation-order-mismatch", "native-action-mismatch",
  "native-identity-mismatch", "native-propagation-mismatch", "native-source-id-leakage",
  "nested-contract-semantic-invalid", "source-hash-mismatch",
  "source-identity-mismatch", "unsupported-action-complement-mismatch",
] as const);
export type LegacyProfileProjectionEnvelopeV1SemanticIssueCode = (typeof LEGACY_PROFILE_PROJECTION_ENVELOPE_V1_SEMANTIC_ISSUE_CODES)[number];
export type LegacyProfileProjectionEnvelopeV1SemanticResult = Readonly<{ok:true;value:SemanticallyValidatedLegacyProfileProjectionEnvelopeV1}>|Readonly<{ok:false;issues:readonly ContractIssue[]}>;
export type LegacyProfileIdV1="legacy-real-estate-v1"|"legacy-municipal-v1"|"legacy-consulting-v1";

type SourceFixture={identity:{domainId:string;profileId:string;modelVersion:string;calibrationVersion:string};applicableDrivers:string[];supportedActionIds:string[];actions:{actionId:string;driverDeltas:Record<string,number>}[];impactContract:{key:string;impacts:{dimension:string;direction:"increase"|"decrease";curve:string}[]}[];curveConfiguration:Record<string,{curve:string;amplitude:{base:number;low:number;high:number;severe:number}}> ;propagationRelationships:{source:string;targets:{target:string;level:string}[]}[];constraints:{refinancingEnabled:boolean;refinancingMarginThreshold:number;activeEffects:Record<string,Record<string,number>>}};
const FIXTURES:Record<LegacyProfileIdV1,SourceFixture>={"legacy-real-estate-v1":realEstateFixture as unknown as SourceFixture,"legacy-municipal-v1":municipalFixture as unknown as SourceFixture,"legacy-consulting-v1":consultingFixture as unknown as SourceFixture};
const SOURCE_HASHES:Record<LegacyProfileIdV1,`sha256:${string}`>={"legacy-real-estate-v1":"sha256:898817bed271a470aecd941612a2bd49a95bec8acf480e5f645ffa0b9b5b33bc","legacy-municipal-v1":"sha256:81ae1fa9f8a21a46c4cd04e4540c98db5750bd1305ecc6e215162d8da634193b","legacy-consulting-v1":"sha256:b1bfcc87c86142264d3bd8d9082475720bdf3dcf8d7d7ec97583a5b40c5e08a7"};
export const LEGACY_DRIVER_ID_MAPPINGS_V1=Object.freeze([["demandRisk","demand-risk"],["pricingPowerRisk","pricing-power-risk"],["tenantStabilityRisk","tenant-stability-risk"],["maintenanceIntensityRisk","maintenance-intensity-risk"],["operationalEfficiencyRisk","operational-efficiency-risk"],["energyExposureRisk","energy-exposure-risk"],["interestRateExposureRisk","interest-rate-exposure-risk"],["leverageLevelRisk","leverage-level-risk"],["refinancingRisk","refinancing-risk"],["marketVolatilityRisk","market-volatility-risk"],["regulatoryPressureRisk","regulatory-pressure-risk"],["capitalCommitmentRigidityRisk","capital-commitment-rigidity-risk"],["accessibility","accessibility"],["modal_attractiveness","modal_attractiveness"],["congestion_pressure","congestion_pressure"],["operational_capacity","operational_capacity"],["transit_signal_priority","transit_signal_priority"],["budget_pressure","budget_pressure"]] as const);
const MAP=new Map<string,string>(LEGACY_DRIVER_ID_MAPPINGS_V1);const BENEFIT=new Set(["accessibility","modal_attractiveness","operational_capacity","transit_signal_priority"]);const mapped=(id:string)=>MAP.get(id)??(id==="liquidityPressure"?"liquidity-pressure":id);const nativeEdgeId=(s:string,t:string)=>`legacy-edge-v1.${mapped(s)}.to.${mapped(t)}`;const compatEdgeId=(s:string,t:string)=>`legacy-compat-edge-v1.${mapped(s)}.to.${mapped(t)}`;
const IGNORED_RE=Object.freeze([{sourceProfileId:"legacy-real-estate-v1",sourceActionId:"stagger_project_starts",sourceDriverId:"implementationPacingRisk",delta:-1},{sourceProfileId:"legacy-real-estate-v1",sourceActionId:"increase_liquidity_buffer",sourceDriverId:"liquidityPressure",delta:-1}]);
const GAP_EFFECTS=Object.freeze([{driverId:"modal_shift_pressure",delta:2},{driverId:"political_feasibility",delta:-1}]);

export function expectedNativeContractV1(profile:LegacyProfileIdV1):DomainModelContractV1{const source=FIXTURES[profile];const projectedDomain=source.identity.domainId==="realEstate"?"real-estate":source.identity.domainId;const drivers=source.applicableDrivers.map(sourceId=>{const driverId=mapped(sourceId);const impact=source.impactContract.find(x=>x.key===sourceId)!;return {driverId,scaleId:"legacy-risk-scale-v1",initial:{levelId:"moderate",score:1},numericRange:{minimum:0,maximum:3},adverseLevelIds:BENEFIT.has(sourceId)?["low"]:["high","severe"],impacts:impact.impacts.map(x=>({dimensionId:x.dimension,direction:x.direction,curveId:`legacy-curve-v1.${driverId}`}))};});
  const admitted=new Set(source.supportedActionIds);const actions=source.actions.filter(x=>admitted.has(x.actionId)&&x.actionId!=="congestion_pricing").map(x=>({actionId:x.actionId,effects:Object.entries(x.driverDeltas).filter(([id])=>MAP.has(id)).map(([id,delta])=>({driverId:mapped(id),delta}))}));
  const edges=source.propagationRelationships.flatMap(x=>x.targets.map(target=>[x.source,target.target] as const)).filter(([s,t])=>s!=="liquidityPressure"&&t!=="liquidityPressure").map(([s,t])=>({edgeId:nativeEdgeId(s,t),sourceDriverId:mapped(s),targetDriverId:mapped(t),triggerLevelIds:BENEFIT.has(s)?["low"]:["high","severe"],propagatedLevelId:"high"}));
  const curves=source.applicableDrivers.map(sourceId=>{const driverId=mapped(sourceId),config=source.curveConfiguration[sourceId];return {curveId:`legacy-curve-v1.${driverId}`,type:config.curve.toLowerCase(),...(config.curve==="EXPONENTIAL"?{exponent:1.2}:config.curve==="LOGISTIC"?{k:.8,x0:3}:{}),amplitudeByLevel:{low:config.amplitude.low,moderate:config.amplitude.base,high:config.amplitude.high,severe:config.amplitude.severe}};});
  const constraints=source.constraints.refinancingEnabled?[{constraintId:"refinancing-constraint",initialLifecycle:"inactive",activation:{kind:"measure-below",measureId:"structural-margin",threshold:.8},sustain:{kind:"until-explicit-transition"},deactivation:{kind:"none"},allowedTransitions:[{from:"inactive",to:"active"},{from:"recovering",to:"active"}],activeEffects:[{dimensionId:"cost",operation:"multiply",value:1.15},{dimensionId:"recovery",operation:"multiply",value:.8}]}]:[];
  return {schemaVersion:"domain-model-contract-v1",engineProtocolVersion:"pulse-domain-engine-protocol-v1",identity:{domainId:projectedDomain,profileId:`${profile}-domain-model-contract-v1`,modelVersion:`${source.identity.modelVersion}-domain-model-contract-v1`,calibrationVersion:`${source.identity.calibrationVersion}-domain-model-contract-v1`,semanticPayloadHash:`sha256:${"0".repeat(64)}`},semanticPayload:{scales:[{scaleId:"legacy-risk-scale-v1",levels:[{levelId:"low",rank:0,anchor:0,materialization:{minimumInclusive:0,maximumExclusive:.5000000000000001}},{levelId:"moderate",rank:1,anchor:1,materialization:{minimumInclusive:.5000000000000001,maximumExclusive:1.5}},{levelId:"high",rank:2,anchor:2,materialization:{minimumInclusive:1.5,maximumExclusive:2.5}},{levelId:"severe",rank:3,anchor:3,materialization:{minimumInclusive:2.5,maximumInclusive:3}}]}],drivers,actions,propagation:{edges,cyclePolicy:"reject",selfEdgePolicy:"reject",duplicateEdgePolicy:"reject"},dimensions:["load","cost","recovery","sensitivity"].map(dimensionId=>({dimensionId,neutralValue:1})),curves:curves as DomainModelContractV1["semanticPayload"]["curves"],constraints:constraints as DomainModelContractV1["semanticPayload"]["constraints"],measures:[{measureId:"structural-margin",kind:"weighted-signal-aggregate-v1",updateOperator:"subtract-terms-add-recovery-v1",initialValue:1,terms:[{termId:"adjusted-cost",source:{kind:"dimension",dimensionId:"cost",stage:"after-constraints"},transform:"deviation-from-neutral",weight:1.2},{termId:"adjusted-recovery",source:{kind:"dimension",dimensionId:"recovery",stage:"after-constraints"},transform:"inverse-from-neutral",weight:1.1},{termId:"positive-adjusted-load",source:{kind:"dimension",dimensionId:"load",stage:"after-constraints"},transform:"positive-deviation-from-neutral",weight:.45},{termId:"base-pressure",source:{kind:"protocol-signal",signalId:"base-dimension-pressure-sum-v1"},transform:"identity",weight:.8}],recovery:{targetValue:1,pull:.12},range:{minimum:-3,maximum:3},escalationRules:source.constraints.refinancingEnabled?[{whenBelow:-1,driverId:"interest-rate-exposure-risk",transitions:[{fromLevelId:"low",toLevelId:"moderate"},{fromLevelId:"moderate",toLevelId:"high"}]}]:[]}]}};}

export function expectedCompatibilityV1(profile:LegacyProfileIdV1){const source=FIXTURES[profile];const ordered=source.propagationRelationships.flatMap((group,sourcePosition)=>group.targets.map((target,edgePosition)=>({sourcePosition,edgePosition,sourceLegacyDriverId:group.source,targetLegacyDriverId:target.target,projectedOrCompatibilityEdgeId:group.source==="liquidityPressure"||target.target==="liquidityPressure"?compatEdgeId(group.source,target.target):nativeEdgeId(group.source,target.target)})));const compat=source.propagationRelationships.flatMap((group,sourcePosition)=>group.targets.map((target,edgePosition)=>({group,target,sourcePosition,edgePosition}))).filter(x=>x.group.source==="liquidityPressure"||x.target.target==="liquidityPressure").map(x=>{const occurrencePosition=ordered.findIndex(y=>y.sourcePosition===x.sourcePosition&&y.edgePosition===x.edgePosition);return {sourcePosition:x.sourcePosition,edgePosition:x.edgePosition,occurrencePosition,sourceLegacySourceDriverId:x.group.source,sourceLegacyTargetDriverId:x.target.target,adapterLocalSourceDriverId:mapped(x.group.source),adapterLocalTargetDriverId:mapped(x.target.target),compatibilityEdgeId:compatEdgeId(x.group.source,x.target.target),sourcePropagatedLevelId:x.target.level,projectedPropagatedLevelId:"high",implicitSourceNodeId:"liquidityPressure",adapterLocalImplicitNodeId:"liquidity-pressure",missingReadDefaultLevelId:"low",materializeOnRaise:true,hasScore:false,hasImpacts:false};});return {ignoredUnknownDriverDeltas:profile==="legacy-real-estate-v1"?IGNORED_RE:[],compatibilityOnlyActions:profile==="legacy-real-estate-v1"?[]:[{kind:"legacy-compatibility-only-action-v1",sourceProfileId:profile,sourceActionId:"congestion_pricing",projectedNativeAction:"omitted-because-no-modeled-effects",admission:"legacy-adapter-only",ignoredEffects:GAP_EFFECTS}],driverIdMappings:LEGACY_DRIVER_ID_MAPPINGS_V1.map(([sourceDriverId,projectedDriverId])=>({sourceDriverId,projectedDriverId})),excludedUnsupportedActionIds:FIXTURES[profile].actions.map(x=>x.actionId).filter(x=>!source.supportedActionIds.includes(x)).sort(compareText),sustainThresholdOverride:source.constraints.refinancingEnabled?{kind:"legacy-risk-state-number-overrides-constraint-threshold-v1",sourceField:"sustainThreshold",constraintId:"refinancing-constraint",acceptedRuntimeType:"number-including-non-finite",comparison:"margin-strictly-below-threshold",applicability:"this-envelope-source-only"}:null,propagation:{edgeEvaluationOrder:"legacy-source-and-target-insertion-order-v1",sourceEvaluationOrder:ordered,compatibilityOnlyEdges:compat},excludedSourceValues:expectedExcluded(profile),curveFallbackDeclaration:{policyId:"legacy-neutral-multiplier-v1",appliesTo:["missing-curve-configuration","unsupported-curve-discriminant"],neutralMultiplier:1,evidenceStatus:"deferred-to-m1e"}};}
function expectedExcluded(profile:LegacyProfileIdV1){const h=(x:unknown)=>`sha256:${hashBaselineValueV1(x)}` as const;const effects=FIXTURES[profile].constraints.activeEffects;const values=[{kind:"provably-unreachable-public-execution-v1",sourcePath:"constraints.LiquidityConstraint",sourceValueHash:h(effects.LiquidityConstraint),reasonCode:"no-public-activation-transition"},{kind:"provably-unreachable-public-execution-v1",sourcePath:"constraints.CovenantConstraint",sourceValueHash:h(effects.CovenantConstraint),reasonCode:"no-public-activation-transition"},{kind:"provably-unreachable-public-execution-v1",sourcePath:"constraints.Custom",sourceValueHash:h({type:"Custom",lifecycle:"INACTIVE",lastUpdatedStep:0}),reasonCode:"inert-global-registry-member"}];if(profile==="legacy-municipal-v1")values.unshift({kind:"provably-unreachable-public-execution-v1",sourcePath:"constraints.RefinancingConstraint",sourceValueHash:h({enabled:false,threshold:.8,effects:effects.RefinancingConstraint}),reasonCode:"profile-constraint-disabled"});return values;}

export function validateLegacyProfileProjectionEnvelopeV1Semantics(input:StructurallyValidatedLegacyProfileProjectionEnvelopeV1):LegacyProfileProjectionEnvelopeV1SemanticResult{const nested=validateDomainModelContractV1Semantics(input.projection.contract);if(!nested.ok)return fail(nested.issues.map(x=>({code:"nested-contract-semantic-invalid",path:`/projection/contract${x.path}`,message:`Nested ${x.code}: ${x.message}`})));const issues:ContractIssue[]=[];const profile=input.source.identity.profileId as LegacyProfileIdV1;const fixture=FIXTURES[profile];if(!fixture)add(issues,"source-identity-mismatch","/source/identity/profileId","Unknown legacy source profile.");else{const expected=expectedNativeContractV1(profile);check(input.source.identity,fixture.identity,"source-identity-mismatch","/source/identity",issues);if(input.source.semanticPayloadHash!==SOURCE_HASHES[profile])add(issues,"source-hash-mismatch","/source/semanticPayloadHash","Source hash differs from the locked M0B hash.");check(input.projection.identity,expected.identity,"native-identity-mismatch","/projection/identity",issues,true);check(nested.value.identity,input.projection.identity,"native-identity-mismatch","/projection/contract/identity",issues,true);const expectedStructural=parseDomainModelContractV1Structure(expected);if(!expectedStructural.ok)throw new Error("Closed expected contract is structurally invalid.");const expectedSemantic=validateDomainModelContractV1Semantics(expectedStructural.value);if(!expectedSemantic.ok)throw new Error("Closed expected contract is semantically invalid.");if(canonicalizeDomainModelContractSemanticIdentityV1(nested.value)!==canonicalizeDomainModelContractSemanticIdentityV1(expectedSemantic.value))classifyNative(input.projection.contract,expected,issues);validateCompatibility(input,profile,issues);}if(issues.length)return fail(issues);const value:RawLegacyProfileProjectionEnvelopeV1={...structuredClone(input),projection:{...structuredClone(input.projection),contract:nested.value}};return Object.freeze({ok:true,value:freeze(value) as SemanticallyValidatedLegacyProfileProjectionEnvelopeV1});}
function classifyNative(actual:DomainModelContractV1,expected:DomainModelContractV1,issues:ContractIssue[]):void{const a=actual.semanticPayload,e=expected.semanticPayload;if(!same(a.scales,e.scales))add(issues,"driver-projection-mismatch","/projection/contract/semanticPayload/scales","Scale projection differs.");if(!same(a.drivers,e.drivers))add(issues,"driver-projection-mismatch","/projection/contract/semanticPayload/drivers","Driver projection differs.");if(!same(a.actions,e.actions))add(issues,"native-action-mismatch","/projection/contract/semanticPayload/actions","Action projection differs.");if(!same(a.propagation,e.propagation))add(issues,"native-propagation-mismatch","/projection/contract/semanticPayload/propagation","Propagation projection differs.");if(!same(a.curves,e.curves))add(issues,"curve-projection-mismatch","/projection/contract/semanticPayload/curves","Curve projection differs.");if(!same(a.constraints,e.constraints))add(issues,"constraint-projection-mismatch","/projection/contract/semanticPayload/constraints","Constraint projection differs.");if(!same(a.measures,e.measures))add(issues,"constraint-projection-mismatch","/projection/contract/semanticPayload/measures","Structural Margin projection differs.");if(!same(a.dimensions,e.dimensions))add(issues,"driver-projection-mismatch","/projection/contract/semanticPayload/dimensions","Dimension projection differs.");}
function validateCompatibility(input:StructurallyValidatedLegacyProfileProjectionEnvelopeV1,profile:LegacyProfileIdV1,issues:ContractIssue[]):void{const actual=input.compatibility,expected=expectedCompatibilityV1(profile);for(const key of ["ignoredUnknownDriverDeltas","compatibilityOnlyActions","driverIdMappings","sustainThresholdOverride","excludedSourceValues","curveFallbackDeclaration"] as const)if(!same(actual[key],expected[key]))add(issues,key==="compatibilityOnlyActions"?"compatibility-action-mismatch":key==="driverIdMappings"?"driver-mapping-mismatch":"compatibility-declaration-mismatch",`/compatibility/${key}`,`${key} differs from the closed profile declaration.`);if(!same(actual.excludedUnsupportedActionIds,expected.excludedUnsupportedActionIds))add(issues,"unsupported-action-complement-mismatch","/compatibility/excludedUnsupportedActionIds","Unsupported action complement differs.");if(!same(actual.propagation,expected.propagation))add(issues,"legacy-propagation-order-mismatch","/compatibility/propagation","Legacy propagation order or compatibility evidence differs.");if(new Set(actual.driverIdMappings.map(x=>x.projectedDriverId)).size!==actual.driverIdMappings.length)add(issues,"driver-mapping-collision","/compatibility/driverIdMappings","Projected driver mappings collide.");const sourceOnly=LEGACY_DRIVER_ID_MAPPINGS_V1.filter(([s,t])=>s!==t).map(([s])=>s);walk(input.projection.contract.semanticPayload,(value,path)=>{if(typeof value==="string"&&(sourceOnly.includes(value as typeof sourceOnly[number])||value==="liquidityPressure"||value==="liquidity-pressure"))add(issues,"native-source-id-leakage",`/projection/contract/semanticPayload${path}`,"Source-only or adapter-local driver ID leaked into native data.");});}
function walk(value:unknown,visit:(value:unknown,path:string)=>void,path=""):void{visit(value,path);if(Array.isArray(value))value.forEach((x,i)=>walk(x,visit,`${path}/${i}`));else if(value&&typeof value==="object")for(const [key,child] of Object.entries(value))walk(child,visit,`${path}/${key.replaceAll("~","~0").replaceAll("/","~1")}`);}
function check(a:unknown,b:unknown,code:LegacyProfileProjectionEnvelopeV1SemanticIssueCode,path:string,issues:ContractIssue[],omitHash=false):void{const strip=(x:unknown)=>{if(!omitHash||!x||typeof x!=="object")return x;const {semanticPayloadHash:ignored,...rest}=x as Record<string,unknown>;void ignored;return rest;};if(!same(strip(a),strip(b)))add(issues,code,path,"Value differs from the closed profile table.");}function same(a:unknown,b:unknown):boolean{return canonicalizeBaselineValueV1(a)===canonicalizeBaselineValueV1(b);}function compareText(left:string,right:string):number{return left<right?-1:left>right?1:0;}function add(i:ContractIssue[],code:LegacyProfileProjectionEnvelopeV1SemanticIssueCode,path:string,message:string):void{i.push({code,path,message});}function fail(i:readonly ContractIssue[]):LegacyProfileProjectionEnvelopeV1SemanticResult{const u=new Map(i.map(x=>[`${x.path}\0${x.code}\0${x.message}`,x]));return Object.freeze({ok:false,issues:Object.freeze(sortContractIssues([...u.values()]))});}function freeze<T>(root:T):T{const stack:object[]=[root as object];while(stack.length){const x=stack.pop()!;if(Object.isFrozen(x))continue;Object.freeze(x);for(const y of Object.values(x))if(y&&typeof y==="object")stack.push(y);}return root;}
